name: CodeGuru Reviewer

on: 
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main
      
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-cachefile-
        restore-keys: ${{ runner.os }}-cachefile-
        
    - name: Setup Python 2.7
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
        
    - name: Install Dependencies
      id: setup-dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      with:
        s3_bucket: codeguru-reviewer-teste-bucket
